name: Build
on:
  pull_request:
  push:
    branches: [main]
    tags: ["v*"]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-large, macos-13-large, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: secondlife/action-autobuild@v4
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: secondlife/action-autobuild-release@v3
